Assignment 1
MukilMuki/Sirius-Java-Training-Assignments pull request #2
Opened 2023-03-20 04:10 UTC by MukilMuki

changed all the review comments

2023-03-20 18:08 UTC, karthik-kantam1117 requested changes

2023-03-20 18:08 UTC, karthik-kantam1117 commented on Assignment-1/Exercise4.java
> +	System.out.println(prim1+" "+prim2+" "+prim3+" "+prim4+" "+prim5+" "+prim6);
use proper naming conventions for variables

2023-03-20 18:08 UTC, karthik-kantam1117 commented on Assignment-1/Exercise6.java
> +
correct Armstrong number logic --> Math.pow(rem,No.of.digits)

2023-03-20 18:08 UTC, karthik-kantam1117 commented on Assignment-1/Exercise8.java
> +		}
Add @override and format you code before using to Github

2023-03-21 10:06 UTC, MukilMuki reviewed
Corrected the changes

2023-03-22 11:53 UTC, karthik-kantam1117 submitted a review, later dismissed
Satisfied with the review changes.

2023-03-22 13:14 UTC, karthik-kantam1117 approved these changes
Satisfied with the review changes.

2023-03-22 13:14 UTC, merged